meta_product_name: "CentrAll"
meta_title: "CentrAll - Quickly find a meeting place"
meta_description: "CentrAll is a mobile website permitting you to easily find a convenient place to meet with your friends"
meta_image: "cover.png"
